gpg_keys:
  - key: https://download.docker.com/linux/ubuntu/gpg

k8s_url_apt_key: "https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key"
k8s_gpgpath: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
k8s_repository: "https://pkgs.k8s.io/core:/stable:/v1.29/deb/"

repositories:
  - repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

https_packages:
  - name: apt-transport-https
  - name: curl

docker_packages:
  - name: docker-ce
  - name: docker-ce-cli
  - name: containerd.io


k8s_packages:
  - name: kubeadm=1.29.*
  - name: kubelet=1.29.*
  - name: kubectl=1.29.*
