- name: Copy the join command to server location
  copy: src=join-command dest=/tmp/join-command.sh

- name: Join the node to cluster
  ansible.builtin.command: sh /tmp/join-command.sh
  changed_when: false
